######################################################################
# Automatically generated by qmake (1.07a) Tue Aug 12 15:50:11 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += src/configconvert
INCLUDEPATH += src/configconvert
QT += xml
OBJECTS_DIR += obj
MOC_DIR += moc


# Input
HEADERS += src/configconvert/configuration.h
SOURCES += src/configconvert/configuration.cpp src/configconvert/main.cpp
