######################################################################
# Automatically generated by qmake (2.01a) Sa Dez 20 13:43:11 2008
######################################################################

TEMPLATE = subdirs
SUBDIRS = prodcalc configconvert
